### ISSUE TITLE
Rework: Ols Module

### ISSUE THREAD

**Issue by iph** [lab-D8/lol-at-pitt#10]
### Description
The current site code is not maintainable. When I made it, I was extremely new to go, mongodb, and no-sql programming. As such, the mongodb instance is made like an SQL database, and is hard to maintain, as is the code behind it (I'm referring to the heavy use of GetXDAO() plaguing the entire code base. 

Fact is, there are few updates (1-2 per hour), but potentially many GETs to the system. We want to work with this, by making one large structure of metadata, with leaf nodes to any real data.

The metadata so far is: Players, Teams, Users and Matches. When I ran some stats on previous seasons, this data combined was less than 500kb. Super small. Real Data: League Games saved to local db. This data was ranging around 5mb for just a few games, ugh. 

There is going to be 2 meta-data stores and 1 data store. OLS and Users. Users need to be separate because they will persist across splits. OLS will store the players, teams and matches within that split. Matches will have references to the game store. I'm still deciding on how to handle games, but that can be part of a separate discussion.

With this in mind, OLS Module is going to wrap our storage and have specific non-DAO public apis that will be able to get the data, and be as flexible as possible.

for now, I'm feeling this API:

```go
ols.GetPlayers(PredicateFunction)
ols.GetMatches(PredicateFunction)
ols.GetTeams(PredicateFunction)
```
This way, we are decoupling our data store from our calls (unlike prior, where we literally got the DAO). The predicate function will allow flexibility (think filter in Java-streams). As for Users, that module will be wrapped with a GetByLeagueId, GetByLeagueName and GetByUserId, just like the current DAO implementation.

Our data store should look something like:
```json
{ 
  "OLS": {
            "Players": [ { "leagueId": 1 }, {"leagueId":2} ],
            "Matches": [{"GameId": 1}, {"GameId": 2} ],
            "Teams": [{"Team": "Cold Ass Honkeys"} ],
            "Split": {
                        "Year": 2015,
                        "Season": "Fall"
             }
   }
}
```

**Comment by zachcd** [comment]
I'll be using this specified api for my development.  If necessary I can implement it, although it will require learning some mongodb.
